version: "3.9"
services:
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
